# Generated by Django 3.2.9 on 2022-05-10 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessions',
            name='numberSession',
        ),
        migrations.AddField(
            model_name='user',
            name='sessionId',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tpm.sessions', verbose_name='Сессия'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='id',
            field=models.AutoField(db_column='Id', primary_key=True, serialize=False),
        ),
    ]
